# Generated by Django 2.1.7 on 2019-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_id',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
