# Generated by Django 2.1.7 on 2019-03-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_success', '0002_remove_order_success_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_success',
            name='bank_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_success',
            name='bank_txn_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_success',
            name='currency',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_success',
            name='gateway_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_success',
            name='order_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_success',
            name='payment_mode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_success',
            name='resp_msg',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order_success',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_success',
            name='txn_amount',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_success',
            name='txn_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_success',
            name='txn_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
